name: Build GlibC for Android

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_android:
    strategy:
      matrix:
        prefix: [ "main" "test" ]
      fail-fast: false

    name: "Build for Android ${{matrix.arch}}"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build with CI build script
      run: bash "build_glibc_${{matrix.prefix}}.sh"
    - name: Upload glibc build output
      uses: actions/upload-artifact@v2
      with:
        name: "glibc-2.35"
        path: glibc-2.35-main.tar.xz
        path: glibc-2.35-test.tar.xz
