name: Build GlibC for Android

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_android:
    strategy:
      matrix:
        prefix: [ "main" ]
      fail-fast: false

    name: "Build GlibC ${{matrix.prefix}}"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build with CI build script
      run: bash "gcc.sh"
    - name: Upload glibc build output
      uses: actions/upload-artifact@v2
      with:
        name: "glibc-2.35"
        path: glibc-*.tar.xz
