name: Build GCC for X86_64-Linux

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_android:
    strategy:
      matrix:
        prefix: [ "main" ]
      fail-fast: false

    name: "Build GCC ${{matrix.prefix}}"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build with build script
      run: bash "gcc.sh"
    - name: Upload build output
      uses: actions/upload-artifact@v2
      with:
        name: "gcc-12.1.0"
        path: glibc-*.tar.xz
