name: get bilibili damaku

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_linux:
    strategy:
      matrix:
        prefix: [ "main" ]
      fail-fast: false

    name: "get damaku"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build with build script
      run: bash "damaku.sh"
    - name: Upload build output
      uses: actions/upload-artifact@v2
      with:
        name: "damaku"
        path: damaku.xml
