#!/bin/bash
export CFLAGS="-O3"
export C_INCLUDE_PATH="$C_INCLUDE_PATH:/usr/local/include/"
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib/"

/home/runner/work/netdisk/netdisk/build-wine/install_32bits_dependencies.sh
cd "/home/runner/work/netdisk/netdisk/build-wine/wine-6.23"
sed -i "s|/tmp|/data/data/com.termux/files/usr/tmp|g" $(find . -name "*.c")
mkdir -p "/home/runner/work/netdisk/netdisk/build-wine/wine-6.23/wine64-build/"
mkdir -p "/home/runner/work/netdisk/netdisk/build-wine/wine-6.23/wine32-build/"

### 64bits build
echo "[STAGE 1/5] Configure 64 bits"
cd "/home/runner/work/netdisk/netdisk/build-wine/wine-6.23/wine64-build/"
../configure --without-unwind --enable-win64 --prefix="/"  LDFLAGS="-L/usr/local/lib"  || exit 4

echo "[STAGE 2/5] Make 64 bits"
make -j 16 || exit 5
make install DESTDIR="/home/runner/work/netdisk/netdisk/build-wine/wine"

### 32bits build
echo "[STAGE 3/5] Installing 32 bits dependencies"

/home/runner/work/netdisk/netdisk/build-wine/install_32bits_dependencies.sh
echo "[STAGE 4/5] Configure 32 bits"
cd "/home/runner/work/netdisk/netdisk/build-wine/wine-6.23/wine32-build/"
../configure --with-wine64=/home/runner/work/netdisk/netdisk/build-wine/wine-6.23/wine64-build --prefix="/" LFFLAGS="-L/usr/local/lib" || exit 6

echo "[STAGE 5/5] Make 32 bits"
make -j 16 || exit 7

