#!/bin/bash
export CFLAGS="-O3"
export C_INCLUDE_PATH="$C_INCLUDE_PATH:/usr/local/include/"
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib/"

cd "/home/runner/work/netdisk/netdisk/build-wine/wine-6.23"
sed "s|/tmp|/data/data/com.termux/files/usr/tmp|g" $(find . -name "*.c")
mkdir -p "/home/runner/work/netdisk/netdisk/build-wine/wine-6.23/wine64-build/"
mkdir -p "/home/runner/work/netdisk/netdisk/build-wine/wine-6.23/wine32-build/"

### 64bits build
echo "[STAGE 1/7] Configure 64 bits"
cd "/home/runner/work/netdisk/netdisk/build-wine/wine-6.23/wine64-build/"
../configure --without-unwind --enable-win64 --prefix="/"  LDFLAGS="-L/usr/local/lib"  || exit 4

echo "[STAGE 2/7] Make 64 bits"
make -j 16 || exit 5

### 32bits build
echo "[STAGE 3/7] Installing 32 bits dependencies"

/home/runner/work/netdisk/netdisk/build-wine/install_32bits_dependencies.sh
echo "[STAGE 4/7] Configure 32 bits"
cd "/home/runner/work/netdisk/netdisk/build-wine/wine-6.23/wine32-build/"
../configure --with-wine64=/home/runner/work/netdisk/netdisk/build-wine/wine-6.23/wine64-build --prefix="/" LFFLAGS="-L/usr/local/lib" || exit 6

echo "[STAGE 5/7] Make 32 bits"
make -j 16 || exit 7

echo "[STAGE 6/7] Make install 64 bits"
cd "/home/runner/work/netdisk/netdisk/build-wine/wine-6.23/wine64-build/"
make install DESTDIR="/home/runner/work/netdisk/netdisk/build-wine/wine" || exit 8

echo "[STAGE 7/7] Make install 32 bits"
cd "/home/runner/work/netdisk/netdisk/build-wine/wine-6.23/wine32-build/"
make install DESTDIR="/home/runner/work/netdisk/netdisk/build-wine/wine" || exit 9
echo "[END]"
